language: node_js
node_js:
  - lts/*
git:
  depth: 3
addons:
  apt:
    packages:
      - expect-dev
cache:
  - pip
  - npm
before_install:
  - openssl aes-256-cbc -K $encrypted_b44033ffb787_key -iv $encrypted_b44033ffb787_iv
    -in .prod.key.json.enc -out .prod.key.json -d
  - gcloud auth activate-service-account --key-file=.prod.key.json
install:
  - npm ci
stages:
  - preparation
  - name: build
    if: branch = production-amp-dev
  - name: deploy
    if: branch = production-amp-dev
jobs:
  include:
    - stage: preparation
      env: APP_ENV=production
      name: Check code, import documents, build samples, playground & boilerplate
      before_script:
        - scripts/unbuffer.sh gulp buildSamples
        - scripts/unbuffer.sh gulp buildPixiFunctions
        - scripts/unbuffer.sh gulp buildComponentVersions
        - scripts/unbuffer.sh npm test
      script:
        - if [ $TRAVIS_BRANCH == "production-amp-dev" ]; then scripts/unbuffer.sh gulp buildPrepare; fi
    - stage: build
      env: APP_ENV=production
      install: &1
        - npm ci
        - python --version
        - PYENV_VERSION=1.2.20
        - PYTHON_VERSION=3.7.8
        - pushd $(pyenv root)
        - git fetch
        - git checkout v$PYENV_VERSION
        - pyenv install -v $PYTHON_VERSION
        - popd
        - pyenv global $PYTHON_VERSION
        - python --version
        - pip install grow==1.0.0 --user
        - export CLOUDSDK_PYTHON=/usr/bin/python
      name: Build Pages (EN)
      script: scripts/unbuffer.sh gulp buildPages --locales en
    - stage: build
      env: APP_ENV=production
      install: *1
      name: Build Pages (DE)
      script: scripts/unbuffer.sh gulp buildPages --locales de
    - stage: build
      env: APP_ENV=staging
      install: *1
      name: Build Pages (FR)
      script: scripts/unbuffer.sh gulp buildPages --locales fr
    - stage: build
      env: APP_ENV=production
      install: *1
      name: Build Pages (AR)
      script: scripts/unbuffer.sh gulp buildPages --locales ar
    - stage: build
      env: APP_ENV=production
      install: *1
      name: Build Pages (ES)
      script: scripts/unbuffer.sh gulp buildPages --locales es
    - stage: build
      env: APP_ENV=production
      install: *1
      name: Build Pages (IT)
      script: scripts/unbuffer.sh gulp buildPages --locales it
    - stage: build
      env: APP_ENV=production
      install: *1
      name: Build Pages (ID)
      script: scripts/unbuffer.sh gulp buildPages --locales id
    - stage: build
      env: APP_ENV=production
      install: *1
      name: Build Pages (JA)
      script: scripts/unbuffer.sh gulp buildPages --locales ja
    - stage: build
      env: APP_ENV=production
      install: *1
      name: Build Pages (KO)
      script: scripts/unbuffer.sh gulp buildPages --locales ko
    - stage: build
      env: APP_ENV=production
      install: *1
      name: Build Pages (BR)
      script: scripts/unbuffer.sh gulp buildPages --locales pt_BR
    - stage: build
      env: APP_ENV=production
      install: *1
      name: Build Pages (RU)
      script: scripts/unbuffer.sh gulp buildPages --locales ru
    - stage: build
      env: APP_ENV=production
      install: *1
      name: Build Pages (TR)
      script: scripts/unbuffer.sh gulp buildPages --locales tr
    - stage: build
      env: APP_ENV=production
      install: *1
      name: Build Pages (CN)
      script: scripts/unbuffer.sh gulp buildPages --locales zh_CN
    - stage: build
      env: APP_ENV=staging
      install: *1
      name: Build Pages (PL)
      script: scripts/unbuffer.sh gulp buildPages --locales pl
    - stage: build
      env: APP_ENV=staging
      install: *1
      name: Build Pages (VN)
      script: scripts/unbuffer.sh gulp buildPages --locales vi
    - stage: deploy
      env: APP_ENV=production
      before_script:
        - rm -rf $HOME/google-cloud-sdk
        - export CLOUDSDK_CORE_DISABLE_PROMPTS=1
        - curl https://sdk.cloud.google.com | bash > /dev/null
        - source /home/travis/google-cloud-sdk/path.bash.inc
        - gcloud version --quiet
        - gcloud components update --quiet
        - gcloud components install beta --quiet
        - gcloud auth activate-service-account --key-file=.prod.key.json
        - gcloud config set project amp-dev-230314
        - scripts/unbuffer.sh gulp buildFinalize
        - scripts/unbuffer.sh npm run smoke-test
      script:
        - scripts/unbuffer.sh gulp deploy
